/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csgo_weapon_database;

import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author Gil
 */


public class GUI extends javax.swing.JFrame {
    String typePilih, weapPilih, mapPilih, weapName, prc, kill, dmg, armorPen, firerate, mob, range, runinacc, inaccjump,
            inaccladder, wantap, wantaphelm;
    rifle rfl = new rifle();
    smg smg = new smg();
    shotgun sgn = new shotgun();
    lmg lmg = new lmg();
    sniper snp = new sniper();
    pistol pistol = new pistol();
    int i;

    

    public void getAllsgn(int i)
    {
        weapName = sgn.weapon[i][0];
        prc = sgn.weapon[i][1];
        kill = sgn.weapon[i][2];
        dmg = sgn.weapon[i][3];
        armorPen = sgn.weapon[i][4];
        firerate = sgn.weapon[i][5];
        mob = sgn.weapon[i][6];
        range = sgn.weapon[i][7];
        runinacc = sgn.weapon[i][8];
        inaccjump = sgn.weapon[i][9];
        inaccladder = sgn.weapon[i][10];
        wantap = sgn.weapon[i][11] + " units";
        wantaphelm = sgn.weapon[i][12] + " units";
        
    }
    
    public void getAllpistol(int i)
    {
        weapName = pistol.weapon[i][0];
        prc = pistol.weapon[i][1];
        kill = pistol.weapon[i][2];
        dmg = pistol.weapon[i][3];
        armorPen = pistol.weapon[i][4];
        firerate = pistol.weapon[i][5];
        mob = pistol.weapon[i][6];
        range = pistol.weapon[i][7];
        runinacc = pistol.weapon[i][8];
        inaccjump = pistol.weapon[i][9];
        inaccladder = pistol.weapon[i][10];
        wantap = pistol.weapon[i][11] + " units";
        wantaphelm = pistol.weapon[i][12] + " units";
        
    }

    
    
    public void getAllsnp(int i)
    {
        weapName = snp.weapon[i][0];
        prc = snp.weapon[i][1];
        kill = snp.weapon[i][2];
        dmg = snp.weapon[i][3];
        armorPen = snp.weapon[i][4];
        firerate = snp.weapon[i][5];
        mob = snp.weapon[i][6];
        range = snp.weapon[i][7];
        runinacc = snp.weapon[i][8];
        inaccjump = snp.weapon[i][9];
        inaccladder = snp.weapon[i][10];
        wantap = snp.weapon[i][11] + " units";
        wantaphelm = snp.weapon[i][12] + " units";
        
    }

    
    public void getAlllmg(int i)
    {
        weapName = lmg.weapon[i][0];
        prc = lmg.weapon[i][1];
        kill = lmg.weapon[i][2];
        dmg = lmg.weapon[i][3];
        armorPen = lmg.weapon[i][4];
        firerate = lmg.weapon[i][5];
        mob = lmg.weapon[i][6];
        range = lmg.weapon[i][7];
        runinacc = lmg.weapon[i][8];
        inaccjump = lmg.weapon[i][9];
        inaccladder = lmg.weapon[i][10];
        wantap = lmg.weapon[i][11] + " units";
        wantaphelm = lmg.weapon[i][12] + " units";
        
    }


    
    public void getAllsmg(int i)
    {
        weapName = smg.weapon[i][0];
        prc = smg.weapon[i][1];
        kill = smg.weapon[i][2];
        dmg = smg.weapon[i][3];
        armorPen = smg.weapon[i][4];
        firerate = smg.weapon[i][5];
        mob = smg.weapon[i][6];
        range = smg.weapon[i][7];
        runinacc = smg.weapon[i][8];
        inaccjump = smg.weapon[i][9];
        inaccladder = smg.weapon[i][10];
        wantap = smg.weapon[i][11] + " units";
        wantaphelm = smg.weapon[i][12] + " units";
        
    }
    public void getAllRfl(int i)
    {
        weapName = rfl.weapon[i][0];
        prc = rfl.weapon[i][1];
        kill = rfl.weapon[i][2];
        dmg = rfl.weapon[i][3];
        armorPen = rfl.weapon[i][4];
        firerate = rfl.weapon[i][5];
        mob = rfl.weapon[i][6];
        range = rfl.weapon[i][7];
        runinacc = rfl.weapon[i][8];
        inaccjump = rfl.weapon[i][9];
        inaccladder = rfl.weapon[i][10];
        wantap = rfl.weapon[i][11] + " units";
        wantaphelm = rfl.weapon[i][12] + " units";
        
    }

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        introPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        mapcalloutPanel = new javax.swing.JPanel();
        mapCombo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        mapimg = new javax.swing.JLabel();
        databasePanel = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        weapNameText = new javax.swing.JLabel();
        prcText = new javax.swing.JLabel();
        killText = new javax.swing.JLabel();
        dmgText = new javax.swing.JLabel();
        armorPenText = new javax.swing.JLabel();
        firerateText = new javax.swing.JLabel();
        mobText = new javax.swing.JLabel();
        rangeText = new javax.swing.JLabel();
        runinaccText = new javax.swing.JLabel();
        inaccjumpText = new javax.swing.JLabel();
        inaccladderText = new javax.swing.JLabel();
        wantapText = new javax.swing.JLabel();
        wantaphelmText = new javax.swing.JLabel();
        ladderinfo = new javax.swing.JButton();
        wantaphelminfo = new javax.swing.JButton();
        wantapinfo = new javax.swing.JButton();
        jumpinfo = new javax.swing.JButton();
        runinfo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        WeapTypeCombo = new javax.swing.JComboBox<>();
        weaponCombo = new javax.swing.JComboBox<>();
        weapimg = new javax.swing.JLabel();
        introButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        weapButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CS:GO Weapon Database");
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mapButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        mapButton.setText("Maps Callout");
        mapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("CS : GO Database");

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/csgo.png"))); // NOI18N

        javax.swing.GroupLayout introPanelLayout = new javax.swing.GroupLayout(introPanel);
        introPanel.setLayout(introPanelLayout);
        introPanelLayout.setHorizontalGroup(
            introPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introPanelLayout.createSequentialGroup()
                .addGap(437, 437, 437)
                .addComponent(jLabel16)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        introPanelLayout.setVerticalGroup(
            introPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introPanelLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel16)
                .addContainerGap(768, Short.MAX_VALUE))
        );

        mainPanel.add(introPanel, "card2");

        mapCombo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        mapCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maps", "Cache", "Dust 2", "Cobblestone", "Inferno", "Mirage", "Overpass", "Train", "Nuke" }));
        mapCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapComboActionPerformed(evt);
            }
        });

        mapimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/ico.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapimg, javax.swing.GroupLayout.DEFAULT_SIZE, 1244, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(mapimg, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mapcalloutPanelLayout = new javax.swing.GroupLayout(mapcalloutPanel);
        mapcalloutPanel.setLayout(mapcalloutPanelLayout);
        mapcalloutPanelLayout.setHorizontalGroup(
            mapcalloutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapcalloutPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(mapcalloutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mapCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        mapcalloutPanelLayout.setVerticalGroup(
            mapcalloutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapcalloutPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(mapCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );

        mainPanel.add(mapcalloutPanel, "card5");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Price");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Kill Award");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Damage (range <500 units)");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Armor Penetration");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Fire Rate (RPM)");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Mobility");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Accurate Range");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Running Inaccuracy");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Inaccuracy at Jump Apex");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Inaccuracy Ladder");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("Fatal Headshot Range");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("Fatal Headshot Range (Helmet)");

        weapNameText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        weapNameText.setText(":");

        prcText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        prcText.setText(":");

        killText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        killText.setText(":");

        dmgText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dmgText.setText(":");

        armorPenText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        armorPenText.setText(":");

        firerateText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        firerateText.setText(":");

        mobText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mobText.setText(":");

        rangeText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rangeText.setText(":");

        runinaccText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        runinaccText.setText(":");

        inaccjumpText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        inaccjumpText.setText(":");

        inaccladderText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        inaccladderText.setText(":");

        wantapText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        wantapText.setText(":");

        wantaphelmText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        wantaphelmText.setText(":");

        ladderinfo.setText("?");
        ladderinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ladderinfoActionPerformed(evt);
            }
        });

        wantaphelminfo.setText("?");
        wantaphelminfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wantaphelminfoActionPerformed(evt);
            }
        });

        wantapinfo.setText("?");
        wantapinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wantapinfoActionPerformed(evt);
            }
        });

        jumpinfo.setText("?");
        jumpinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumpinfoActionPerformed(evt);
            }
        });

        runinfo.setText("?");
        runinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runinfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wantaphelminfo))
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ladderinfo))
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wantapinfo))
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jumpinfo))
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(runinfo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prcText)
                    .addComponent(weapNameText)
                    .addComponent(killText)
                    .addComponent(inaccjumpText)
                    .addComponent(inaccladderText)
                    .addComponent(wantaphelmText)
                    .addComponent(dmgText)
                    .addComponent(armorPenText)
                    .addComponent(firerateText)
                    .addComponent(mobText)
                    .addComponent(rangeText)
                    .addComponent(runinaccText)
                    .addComponent(wantapText))
                .addGap(298, 298, 298))
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(weapNameText))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prcText))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(killText))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dmgText))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(armorPenText))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(firerateText))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(mobText))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rangeText))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(runinaccText)
                    .addComponent(runinfo))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(inaccjumpText)
                    .addComponent(jumpinfo))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(inaccladderText)
                    .addComponent(ladderinfo))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(wantapText)
                    .addComponent(wantapinfo))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(wantaphelmText)
                    .addComponent(wantaphelminfo))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("Select a weapon :");

        WeapTypeCombo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        WeapTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type", "Pistols", "Shotguns", "SMGs", "Auto Rifles", "Sniper Rifles", "LMGs" }));
        WeapTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeapTypeComboActionPerformed(evt);
            }
        });

        weaponCombo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        weaponCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        weaponCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weaponComboActionPerformed(evt);
            }
        });

        weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/ico.png"))); // NOI18N
        weapimg.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout databasePanelLayout = new javax.swing.GroupLayout(databasePanel);
        databasePanel.setLayout(databasePanelLayout);
        databasePanelLayout.setHorizontalGroup(
            databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databasePanelLayout.createSequentialGroup()
                .addGroup(databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(databasePanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addGap(54, 54, 54)
                        .addComponent(WeapTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(weaponCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(databasePanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(weapimg)))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        databasePanelLayout.setVerticalGroup(
            databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, databasePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(WeapTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weaponCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(databasePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(341, 341, 341))
                    .addGroup(databasePanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(weapimg, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(383, Short.MAX_VALUE))))
        );

        mainPanel.add(databasePanel, "card2");

        introButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        introButton.setText("Intro");
        introButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introButtonActionPerformed(evt);
            }
        });

        aboutButton.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        weapButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        weapButton.setText("Weapon Database");
        weapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weapButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(118, 118, 118)
                        .addComponent(introButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(weapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(mapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(aboutButton)))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aboutButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(introButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WeapTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeapTypeComboActionPerformed
        // TODO add your handling code here:

        typePilih = (String) WeapTypeCombo.getSelectedItem();
        switch (typePilih){
        case "Pistols":
            weaponCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weapon", "Deagle", "Revolver", "Dualist", "Five-SeveN", "Glock", "P2000", "USP-S", "P250", "CZ75 Auto", "Tec-9"}));
            break;
        case "Shotguns":
            weaponCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weapon", "Mag-7", "Nova", "Sawed-Off","XM1014"}));
            break;
        case "SMGs":
            weaponCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weapon", "PP-Bizon", "MAC-10", "MP7","MP5-SD", "MP9", "P90", "UMP-45"}));
            break;
        case "Auto Rifles":
            weaponCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weapon", "AK-47", "AUG", "FAMAS","Galil", "M4A4", "M4A1-S", "SG 553"}));
            break;
        case "Sniper Rifles":
            weaponCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weapon", "AWP", "CT Geigun", "T Geigun","SSG 08"}));
            break;
        case "LMGs":
            weaponCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weapon", "M249", "Negev"}));
            break;
        }
    }//GEN-LAST:event_WeapTypeComboActionPerformed

    private void weaponComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weaponComboActionPerformed
        // TODO add your handling code here:
        weapPilih = (String) weaponCombo.getSelectedItem();
        switch (weapPilih){
            
        //Pistols
        case "Deagle":
            getAllpistol(0);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/pistol/deagle.jpg")));
        break;
        
        case "Revolver":
            getAllpistol(1);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/pistol/r8.jpg")));
        break;            
        
        case "Dualist":
            getAllpistol(2);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/pistol/dualist.jpg")));
        break;        
        
        case "Five-SeveN":
            getAllpistol(3);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/pistol/57.jpg")));
        break;        
        
        case "Glock":
            getAllpistol(4);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/pistol/glock.jpg")));
        break;        
        
        case "P2000":
            getAllpistol(5);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/pistol/p2k.jpg")));
        break;  
        
        case "USP-S":
            getAllpistol(6);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/pistol/usp.jpg")));
        break;
        
        case "P250":
            getAllpistol(7);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/pistol/p250.jpg")));
        break;
        
        case "CZ75 Auto":
            getAllpistol(8);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/pistol/czauto.jpg")));
        break;
        
        case "Tec-9":
            getAllpistol(9);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/pistol/tec9.jpg")));
        break;
        

            
            
            
         
            
        //rifle
        case "AK-47":
            getAllRfl(0);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/rfl/ak47.jpg")));
        break;
        
        case "AUG":
            getAllRfl(1);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/rfl/aug.jpg")));
        break;            
        
        case "FAMAS":
            getAllRfl(2);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/rfl/famas.jpg")));
        break;        
        
        case "Galil":
            getAllRfl(3);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/rfl/galil.jpg")));
        break;        
        
        case "M4A4":
            getAllRfl(4);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/rfl/m4a4.jpg")));
        break;        
        
        case "M4A1-S":
            getAllRfl(5);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/rfl/m4a1s.jpg")));
        break;  
        
        case "SG 553":
            getAllRfl(6);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/rfl/sg553.jpg")));
        break;

        
        
        //sniper
        case "AWP":
            getAllsnp(0);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/snp/awp.jpg")));
        break;
        
        case "T Geigun":
            getAllsnp(1);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/snp/tgay.jpg")));
        break;            
        
        case "CT Geigun":
            getAllsnp(2);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/snp/ctgay.jpg")));
        break;        
        
        case "SSG 08":
            getAllsnp(3);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/snp/ssg.jpg")));
        break;        
        
        
        
        
        //smg
        case "PP-Bizon":
            getAllsmg(0);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/smg/pp.jpg")));
        break;
        
        case "MAC-10":
            getAllsmg(1);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/smg/mac10.jpg")));
        break;            
        
        case "MP7":
            getAllsmg(2);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/smg/mp7.jpg")));
        break;        
        
        case "MP5-SD":
            getAllsmg(3);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/smg/mp5sd.jpg")));
        break;        
        
        case "MP9":
            getAllsmg(4);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/smg/mp9.jpg")));
        break;        
        
        case "P90":
            getAllsmg(5);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/smg/p90.jpg")));
        break;  
        
        case "UMP-45":
            getAllsmg(6);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/smg/ump45.jpg")));
        break;  
        
        
        
        //shotguns
        case "Mag-7":
            getAllsgn(0);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/sgn/mag7.jpg")));
        break;
        
        case "Nova":
            getAllsgn(1);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/sgn/nova.jpg")));
        break;            
        
        case "Sawed-Off":
            getAllsgn(2);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/sgn/sawedoff.jpg")));
        break;        
        
        case "XM1014":
            getAllsgn(3);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/sgn/xm.jpg")));
        break;        
        
        
        
        
       //lmg
        case "M249":
            getAlllmg(0);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/lmg/m249.jpg")));
        break;
        
        case "Negev":
            getAlllmg(1);
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/lmg/negev.jpg")));
        break; 
        
        case "Weapon":
            weapName = (""); prc = (""); kill = (""); dmg = (""); armorPen = (""); firerate = (""); mob = (""); range = (""); runinacc = (""); inaccjump = ("");
            inaccladder = (""); wantap = (""); wantaphelm = ("");
            weapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/ico.png")));

        break;
            
        }
        
        weapNameText.setText(": "+weapName);
        prcText.setText(": "+prc);
        killText.setText(": "+kill);
        dmgText.setText(": "+dmg);
        armorPenText.setText(": "+armorPen);
        firerateText.setText(": "+firerate);
        mobText.setText(": "+mob);
        rangeText.setText(": "+range);
        runinaccText.setText(": "+runinacc);
        inaccjumpText.setText(": "+inaccjump);
        inaccladderText.setText(": "+inaccladder);
        wantapText.setText(": "+wantap);
        wantaphelmText.setText(": "+wantaphelm);
        
        

    }//GEN-LAST:event_weaponComboActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(GUI.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void introButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introButtonActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(introPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_introButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        // TODO add your handling code here:
        new aboutFrame().setVisible(true);
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void mapComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapComboActionPerformed
        // TODO add your handling code here:
        mapPilih = (String) mapCombo.getSelectedItem();
        switch (mapPilih){
        
        case "Cache":
            mapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/map/cache.png")));
        break;
        
        case "Cobblestone":
            mapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/map/cbble.png")));
        break;            
        
        case "Dust 2":
            mapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/map/dust2.png")));
        break;      
        
        case "Inferno":
            mapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/map/inferno.png")));
        break;
        
        case "Mirage":
            mapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/map/mirage.png")));
        break;            
        
        case "Nuke":
            mapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/map/nuke.png")));
        break;     
        
        case "Overpass":
            mapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/map/overpass.png")));
        break;
        
        case "Train":
            mapimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csgo_weapon_database/imgsrc/map/train.png")));
        break;            
        
        }
    }//GEN-LAST:event_mapComboActionPerformed

    private void mapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapButtonActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(mapcalloutPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        
    }//GEN-LAST:event_mapButtonActionPerformed

    private void weapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weapButtonActionPerformed
        // TODO add your handling code here:
                mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(databasePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_weapButtonActionPerformed

    private void ladderinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ladderinfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Lower is better.\nYou loss your accuracy on ladder.\nSome weapon has the ability to maintains its accuracy on a ladder.\n"
                + "\nBest on ladder accuracy (excluding revolver) : MAC-10 (69.12)"
        ,"Ladder Inaccuracy Information",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ladderinfoActionPerformed

    private void wantaphelminfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wantaphelminfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Range you can one tap enemy.\nBut now the enemy wears a helmet.\n"
                + "\nLongest fatal headshot with helmet range (excluding sniper rifle) : SG553 (4,512.31) units"
        ,"Fatal Headshot with Helmet Information",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_wantaphelminfoActionPerformed

    private void wantapinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wantapinfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Range you can one tap enemy\n"
                + "\nLongest fatal headshot range (excluding sniper rifle) : AK-47 (9,024.61) units"
        ,"Fatal Headshot Information",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_wantapinfoActionPerformed

    private void jumpinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumpinfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Lower is better.\nYou have better accuracy at apex of your jump."
                + "\nBest accuracy at jump apex : SSG 08 (8.95)(Scoped)"
        ,"Inaccuracy at Jump Apex Information",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jumpinfoActionPerformed

    private void runinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runinfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Lower is better.\nMost of pistols and smgs are safe enough to run and gun\n"
                + "\nBest running accuracy (pistols) : R8 Revolver (9.02)(Left-click), Tec-9 (10.71)"
                + "\nSMGs : MAC-10 (27.89)"
        ,"Running Inaccuracy Information",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_runinfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> WeapTypeCombo;
    public javax.swing.JButton aboutButton;
    public javax.swing.JLabel armorPenText;
    public javax.swing.JPanel dataPanel;
    public javax.swing.JPanel databasePanel;
    public javax.swing.JLabel dmgText;
    public javax.swing.JLabel firerateText;
    public javax.swing.JLabel inaccjumpText;
    public javax.swing.JLabel inaccladderText;
    public javax.swing.JButton introButton;
    public javax.swing.JPanel introPanel;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JButton jumpinfo;
    public javax.swing.JLabel killText;
    public javax.swing.JButton ladderinfo;
    public javax.swing.JPanel mainPanel;
    public javax.swing.JButton mapButton;
    public javax.swing.JComboBox<String> mapCombo;
    public javax.swing.JPanel mapcalloutPanel;
    public javax.swing.JLabel mapimg;
    public javax.swing.JLabel mobText;
    public javax.swing.JLabel prcText;
    public javax.swing.JLabel rangeText;
    public javax.swing.JLabel runinaccText;
    public javax.swing.JButton runinfo;
    public javax.swing.JLabel wantapText;
    public javax.swing.JLabel wantaphelmText;
    public javax.swing.JButton wantaphelminfo;
    public javax.swing.JButton wantapinfo;
    public javax.swing.JButton weapButton;
    public javax.swing.JLabel weapNameText;
    public javax.swing.JLabel weapimg;
    public javax.swing.JComboBox<String> weaponCombo;
    // End of variables declaration//GEN-END:variables
}
